// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Ucr7mfSh0xV6pwAUFl6F-RMdc44W_FI',
    appId: '1:1052909391936:web:91ab3daac7e7f427d38fa5',
    messagingSenderId: '1052909391936',
    projectId: 'xhat-8173d',
    authDomain: 'xhat-8173d.firebaseapp.com',
    storageBucket: 'xhat-8173d.firebasestorage.app',
    measurementId: 'G-7Z86D3EJ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBE7DRlbKnyP-AQnTBuDaeU1uBDV94cE',
    appId: '1:1052909391936:android:d729208e9283d4cdd38fa5',
    messagingSenderId: '1052909391936',
    projectId: 'xhat-8173d',
    storageBucket: 'xhat-8173d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Ucr7mfSh0xV6pwAUFl6F-RMdc44W_FI',
    appId: '1:1052909391936:web:cbd00bd5bfe9681ed38fa5',
    messagingSenderId: '1052909391936',
    projectId: 'xhat-8173d',
    authDomain: 'xhat-8173d.firebaseapp.com',
    storageBucket: 'xhat-8173d.firebasestorage.app',
    measurementId: 'G-HZEQ4H521E',
  );
}
